server:
  port: 8080

spring:
  application:
    name: aura-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db.rgohkhuqxitungrwanhv.supabase.co:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:xxFgCAGj6Js4MaDs}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:aura_secret_key_which_should_be_at_least_256_bits_long_for_security_and_production_grade_deployment}
    expiration-ms: 86400000
